name = "Meshes"
uuid = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
authors = ["JÃºlio Hoffimann and contributors"]
version = "0.55.1"

[deps]
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
CircularArrays = "7a955b69-7140-5f4e-a0ed-f168c5e2e749"
Colorfy = "03fe91ce-8ec6-4610-8e8d-e7491ccca690"
CoordRefSystems = "b46f11dc-f210-4604-bfba-323c1ec968cb"
DelaunayTriangulation = "927a84f5-c5f4-47a5-9785-b46e178433df"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
ScopedValues = "7e506255-f358-4e82-b7e4-beb19740aa63"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TiledIteration = "06e1c1a7-607b-532d-9fad-de7d9aa2abac"
TransformsBase = "28dd2a49-a57a-4bfb-84ca-1a49db9b96b8"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Bessels = "0.2"
CircularArrays = "1.3"
Colorfy = "1.1"
CoordRefSystems = "0.19"
DelaunayTriangulation = "1.0"
Distances = "0.10"
LinearAlgebra = "1.10"
Makie = "0.24"
NearestNeighbors = "0.4"
Random = "1.10"
Rotations = "1.5.1"
ScopedValues = "1.2"
SparseArrays = "1.10"
StaticArrays = "1.0"
StatsBase = "0.33, 0.34"
TiledIteration = "0.5"
TransformsBase = "1.6"
Unitful = "1.17"
julia = "1.10"

[extensions]
MeshesMakieExt = "Makie"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
