name = "Meshes"
uuid = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
authors = ["JÃºlio Hoffimann and contributors"]
version = "0.26.3"

[deps]
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
CircularArrays = "7a955b69-7140-5f4e-a0ed-f168c5e2e749"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReferenceFrameRotations = "74f56ac7-18b3-5285-802d-d4bd4f104033"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TransformsBase = "28dd2a49-a57a-4bfb-84ca-1a49db9b96b8"

[compat]
Bessels = "0.2"
CircularArrays = "1.3"
Distances = "0.10"
IterTools = "1.3"
NearestNeighbors = "0.4"
ReferenceFrameRotations = "3"
StaticArrays = "1.0"
StatsBase = "0.33"
Tables = "1.8"
TransformsBase = "0.1"
julia = "1.6"
