name = "Meshes"
uuid = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
authors = ["JÃºlio Hoffimann and contributors"]
version = "0.17.26"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
CircularArrays = "7a955b69-7140-5f4e-a0ed-f168c5e2e749"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
ReferenceFrameRotations = "74f56ac7-18b3-5285-802d-d4bd4f104033"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CategoricalArrays = "0.10"
CircularArrays = "1.3"
Distances = "0.10"
IterTools = "1.3"
IteratorInterfaceExtensions = "1.0"
NearestNeighbors = "0.4"
RecipesBase = "1.1"
ReferenceFrameRotations = "0.5, 1.0, 2"
SimpleTraits = "0.9"
SpecialFunctions = "0.10, 1.1"
StaticArrays = "0.12, 1.0"
StatsBase = "0.33"
TableTraits = "1.0"
Tables = "1.3"
julia = "1.5"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Test", "Random"]
